### ISSUE TITLE
Placement of character always at the end.

### ISSUE THREAD

**Issue by s1390** [Xesyto/Hexchat-DeadKeyFix#3]
Hello,

Thank you very much for this addon (and thanks to @Joeytje50 for revamping this).

Now the issue is as follows: when you type in a long sentence, and you want to place a `'` somewhere in the sentence, it'll always auto-place the `'` at end of the sentence (and not where your pointer is).

Thanks in advance!

**Comment by Xesyto** [comment]
You are correct. In retrospect I'd noticed this before but had not attributed it to this addon. Thanks for the heads up.

**Comment by s1390** [comment]
Thank you, this solved the problem. 
However, there's a different issue now. When typing for example: `It's`, it will place the cursor after the `'`, and not after the `s`, like it did earlier.

**Comment by Xesyto** [comment]
I basically reflexively use a space whenever I'm trying to input just a ' or something like that.

However I'm currently working on some other things to make the plugin more robust and I'll get this behavior straightened out.

**Comment by s1390** [comment]
Awesome, thanks again.

**Comment by Xesyto** [comment]
I hope the latest version fixes any problems you have ( it should ). If not you know how to open more Issues.

**Comment by s1390** [comment]
I just tested it, and everything works now!

Thank you.
